services:
  - type: web
    name: job-management-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://admin-interface-alpha.vercel.app,http://localhost:3000
      - key: DATABASE_URL
        value: postgresql://job_management_user:Mji3z4zb4gSxzMnSShmNiwfcJVrumb4I@dpg-d2ctl5k9c44c73b2vod0-a.singapore-postgres.render.com/job_management_5mlx
