services:
  - type: web
    name: job-management-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: https://admin-interface-alpha.vercel.app,http://localhost:3000
      # Database configuration will be set from the PostgreSQL service
      - key: DB_HOST
        fromDatabase:
          name: job-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: job-management-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: job-management-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: job-management-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: job-management-db
          property: database

databases:
  - name: job-management-db
    plan: free
    databaseName: job_management
    user: job_management_user
